#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-hostkeys-install() {
  declare desc="installs the hostkeys"
  declare trigger="install"

  SHARED_HOSTKEYS_FOLDER="$DOKKU_ROOT/.hostkeys/shared/.ssh"

  if [[ ! -d "$SHARED_HOSTKEYS_FOLDER" ]]; then
    install -d -m 0700 "$SHARED_HOSTKEYS_FOLDER"
  fi

  if [[ ! -f "$SHARED_HOSTKEYS_FOLDER/known_hosts" ]]; then
    install -m 0600 /dev/null "$SHARED_HOSTKEYS_FOLDER/known_hosts"
  fi

  chown -R dokku:dokku "$DOKKU_ROOT/.hostkeys"
}

trigger-hostkeys-install "$@"
