#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

SHARED_HOSTKEYS_FOLDER="$DOKKU_ROOT/.hostkeys/shared/.ssh"

if [[ ! -d "$SHARED_HOSTKEYS_FOLDER" ]]
 then
  mkdir -p "$SHARED_HOSTKEYS_FOLDER";
fi

if [[ ! -f "$SHARED_HOSTKEYS_FOLDER/known_hosts" ]]
 then
  touch "$SHARED_HOSTKEYS_FOLDER/known_hosts";
fi

chown -R dokku:dokku "$DOKKU_ROOT/.hostkeys"
