#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-hostkeys-install() {
  declare desc="installs the hostkeys"
  declare trigger="install"

  SHARED_HOSTKEYS_FOLDER="$DOKKU_ROOT/.hostkeys/shared/.ssh"
  mkdir -p "$SHARED_HOSTKEYS_FOLDER"
  mkdir -p "$PLUGIN_CONFIG_ROOT"

  if [[ ! -f "$SHARED_HOSTKEYS_FOLDER/known_hosts" ]]; then
    touch "$SHARED_HOSTKEYS_FOLDER/known_hosts"
  fi

  chown -R dokku:dokku "$DOKKU_ROOT/.hostkeys"
}

trigger-hostkeys-install "$@"
